Repository googleapis/python-debugger-client, pull requests merged in 2021-08, with the labels that each got.

#18 feat: bump release level to production/stable
  .repo-metadata.json
  README.rst
  docs/README.rst
  setup.py
Labels: api: clouddebugger, automerge, cla: yes

#22 chore: generate python samples templates in owlbot.py
  owlbot.py
Labels: automerge, cla: yes, samples, api: clouddebugger

#23 chore: migrate default branch from master to main
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  owlbot.py
Labels: cla: yes, api: clouddebugger
